### ISSUE TITLE
This structure duplicates the PID's of the lights. Could this be cleaned up?

### ISSUE THREAD

**Issue by michelgrootjans** [michelgrootjans/nerves-projects#1]
https://github.com/michelgrootjans/nerves-projects/blob/3c401c261b7a0d6231709273d82e99f9a5f72641/traffic_light/lib/traffic_light/blinker.ex#L21

**Comment by tcoopman** [comment]
1. You're not using the pids in the queue? So you can just remove it?
2. You could extract the logic of picking a the next light in a separate module (the queue). I'm not saying you should do this, but this makes it easy to test the queue implementation.
